//
// Created by FINNSEEFLY on 21.11.2020.
//

#ifndef ARKANOID_RESOURCES_H
#define ARKANOID_RESOURCES_H
enum BonusType {
    BONUS_EXPAND,
    BONUS_CUT,
    BONUS_EXPERIENCE_100,
    BONUS_EXPERIENCE_500,
    BONUS_EXPERIENCE_1000,
    BONUS_FIREBALL,
    BOUNS_SHOOTING
};

#define BLOCK_NULL 0
#define BLOCK_PURPLE 1
#define BLOCK_BLUE 2
#define BLOCK_GREEN 3
#define BLOCK_YELLOW 4
#define BLOCK_RED 5


#define TEXT_ZONE_HEIGHT 65
#define TEXT_TOP 64
#define TEXT_BOTTOM 128
#define LEVEL_LEFT 20
#define LEVEL_RIGHT 156
#define SCORE_LEFT 217
#define SCORE_RIGHT 863
#define LIVES_LEFT 923
#define LIVES_RIGHT 1059

#define DEFAULT_FONT_HEIGHT 55
#define DEFAULT_FONT_WIDTH 30
#define DEFAULT_FONT_WEIGHT 32
#define DEFAULT_FONT_ESCAPEMENT 0
#define DEFAULT_FONT_UNDERLINE false
#define DEFAULT_FONT_STRIKE_OUT false
#define DEFAULT_FONT_ITALIC false

#define DEFAULT_GAME_ZONE_TOP 150

#define DEFAULT_PLATFORM_OFFSET_X 432
#define DEFAULT_PLATFORM_OFFSET_Y 890


#endif //ARKANOID_RESOURCES_H
