//
// Created by FINNSEEFLY on 21.11.2020.
//

#ifndef ARKANOID_RESOURCES_H
#define ARKANOID_RESOURCES_H

enum BonusType {
    BONUS_EXPAND,
    BONUS_CUT,
    BONUS_EXPERIENCE_100,
    BONUS_EXPERIENCE_500,
    BONUS_EXPERIENCE_1000,
    BONUS_FIREBALL,
    BOUNS_SHOOTING
};


#endif //ARKANOID_RESOURCES_H
